### ISSUE TITLE
0 bleu score error

### ISSUE THREAD

**Issue by magrenimish** [anhtu96/machine-translation#1]
Hi there, Thanks for this comprehensive work. I ran the .pynb notebook but with both the models, I get a bleu score of zero on the validation data after every epoch and the test data as well. Have you faced this error?

**Comment by anhtu96** [comment]
> 

Hi, thanks for your feedback. I tried to re-run the notebook today and experience the same behavior as yours, I guess maybe there are some changes in PyTorch since this notebook was written in old version. I will inspect on this, thank you!

**Comment by anhtu96** [comment]
> Hi there, Thanks for this comprehensive work. I ran the .pynb notebook but with both the models, I get a bleu score of zero on the validation data after every epoch and the test data as well. Have you faced this error?

Hi, thanks for your feedback. I tried to re-run the notebook today and experience the same behavior as yours, I guess maybe there are some changes in PyTorch since this notebook was written in old version. I will inspect on this, thank you!

**Comment by anhtu96** [comment]
So the temporary solution is you can try to use old version of PyTorch first, 1.2.0 or 1.3.0 are both OK. I tested them.
https://pytorch.org/get-started/previous-versions/
